### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

### ISSUE THREAD

**Issue by cmxnono** [OpenTeleVision/TeleVision#16]
Hi, 

Is anything wrong with resource file?
Here is my log on screen.
```
python3 teleop_hand_neo.py 
Importing module 'gym_38' (/home/chenxiu/src/robot/television/TeleVision/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/chenxiu/src/robot/television/TeleVision/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 2.3.0+cu121
Device count 1
/home/chenxiu/src/robot/television/TeleVision/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/chenxiu/.cache/torch_extensions/py38_cu121 as PyTorch extensions root...
Emitting ninja build file /home/chenxiu/.cache/torch_extensions/py38_cu121/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
Serving file:///home/chenxiu/src/robot/television/TeleVision/teleop at /static
Visit: https://vuer.ai?grid=False
Traceback (most recent call last):
  File "teleop_hand_neo.py", line 255, in <module>
    teleoperator = VuerTeleop('inspire_hand.yml')
  File "teleop_hand_neo.py", line 43, in __init__
    self.left_retargeting = left_retargeting_config.build()
  File "/home/chenxiu/miniconda3/envs/tv/lib/python3.8/site-packages/dex_retargeting/retargeting_config.py", line 139, in build
    robot_urdf = urdf.URDF.load(self.urdf_path)
  File "/home/chenxiu/miniconda3/envs/tv/lib/python3.8/site-packages/dex_retargeting/yourdfpy.py", line 950, in load
    return URDF(robot=URDF._parse_robot(xml_element=xml_root), **kwargs)
  File "/home/chenxiu/miniconda3/envs/tv/lib/python3.8/site-packages/dex_retargeting/yourdfpy.py", line 606, in __init__
    self._scene = self._create_scene(
  File "/home/chenxiu/miniconda3/envs/tv/lib/python3.8/site-packages/dex_retargeting/yourdfpy.py", line 1248, in _create_scene
    matrix, _ = self._forward_kinematics_joint(j)
  File "/home/chenxiu/miniconda3/envs/tv/lib/python3.8/site-packages/dex_retargeting/yourdfpy.py", line 1018, in _forward_kinematics_joint
    matrix = origin @ tra.rotation_matrix(q, joint.axis)
  File "/home/chenxiu/miniconda3/envs/tv/lib/python3.8/site-packages/trimesh/transformations.py", line 373, in rotation_matrix
    M = np.diag([cosa, cosa, cosa, 1.0])
  File "<__array_function__ internals>", line 200, in diag
  File "/home/chenxiu/miniconda3/envs/tv/lib/python3.8/site-packages/numpy/lib/twodim_base.py", line 295, in diag
    v = asanyarray(v)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.
/home/chenxiu/miniconda3/envs/tv/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by cmxnono** [comment]
An environment error

**Comment by 7anmay** [comment]
You probably using the wrong version of numpy required for dex-retargeting.

**Comment by csjiyw** [comment]
numpy version should be 1.22.0

**Comment by IvyerS** [comment]
> An environment error
did you solve it by change the numpy version from1.23.0 to 1.22.0?
