### ISSUE TITLE
  File "/home/rob/anaconda3/envs/tv/lib/python3.8/site-packages/vuer/base.py", line 124, in init_server     ssl_context.load_cert_chain(certfile=self.cert, keyfile=self.key) FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by dbdxnuliba** [OpenTeleVision/TeleVision#18]
(tv) rob@rob_sir:~/rl/TeleVision/teleop$ python teleop_hand.py 
Importing module 'gym_38' (/home/rob/rl/IsaacGym_Preview_4_Package/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/rob/rl/IsaacGym_Preview_4_Package/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 2.3.0+cu121
Device count 1
/home/rob/rl/IsaacGym_Preview_4_Package/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/rob/.cache/torch_extensions/py38_cu121 as PyTorch extensions root...
Emitting ninja build file /home/rob/.cache/torch_extensions/py38_cu121/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
Serving file:///home/rob/rl/TeleVision/teleop at /static
Visit: https://vuer.ai?grid=False
Process Process-1:
Traceback (most recent call last):
  File "/home/rob/anaconda3/envs/tv/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rob/anaconda3/envs/tv/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rob/rl/TeleVision/teleop/TeleVision.py", line 78, in run
    self.app.run()
  File "/home/rob/anaconda3/envs/tv/lib/python3.8/site-packages/vuer/server.py", line 766, in run
    super().run()
  File "/home/rob/anaconda3/envs/tv/lib/python3.8/site-packages/vuer/base.py", line 136, in run
    event_loop.run_until_complete(init_server())
  File "/home/rob/anaconda3/envs/tv/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/rob/anaconda3/envs/tv/lib/python3.8/site-packages/vuer/base.py", line 124, in init_server
    ssl_context.load_cert_chain(certfile=self.cert, keyfile=self.key)
FileNotFoundError: [Errno 2] No such file or directory
/home/rob/anaconda3/envs/tv/lib/python3.8/site-packages/numpy/lib/twodim_base.py:295: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  v = asanyarray(v)
[2024-07-18 16:13:06.661] [SAPIEN] [warning] A second engine will share the same internal structures with the first one. Arguments passed to constructor will be ignored.
Not connected to PVD
+++ Using GPU PhysX
Physics Engine: PhysX
Physics Device: cuda:0
GPU Pipeline: disabled
teleop_hand.py:111: DeprecationWarning: an integer is required (got type isaacgym._bindings.linux-x86_64.gym_38.DofDriveMode).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  asset_options.default_dof_drive_mode = gymapi.DOF_MODE_POS

**Comment by chengxuxin** [comment]
You need to check if you have used mkcert to generate `key.pem` and `cert.pem` and put them in the corresponding location.
